/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotAuthorizedRouteImport } from './routes/not-authorized'
import { Route as AdminLogoutRouteImport } from './routes/admin-logout'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSuppliersIndexRouteImport } from './routes/admin/suppliers/index'
import { Route as AdminStockBatchesIndexRouteImport } from './routes/admin/stock-batches/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductVariantsIndexRouteImport } from './routes/admin/product-variants/index'
import { Route as AdminManufacturersIndexRouteImport } from './routes/admin/manufacturers/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSuppliersNewRouteImport } from './routes/admin/suppliers/new'
import { Route as AdminSuppliersSupplierIdRouteImport } from './routes/admin/suppliers/$supplierId'
import { Route as AdminStockBatchesNewRouteImport } from './routes/admin/stock-batches/new'
import { Route as AdminStockBatchesStockBatchIdRouteImport } from './routes/admin/stock-batches/$stockBatchId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductVariantsNewRouteImport } from './routes/admin/product-variants/new'
import { Route as AdminProductVariantsProductVariantIdRouteImport } from './routes/admin/product-variants/$productVariantId'
import { Route as AdminManufacturersNewRouteImport } from './routes/admin/manufacturers/new'
import { Route as AdminManufacturersManufacturerIdRouteImport } from './routes/admin/manufacturers/$manufacturerId'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin/categories/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/product.$id'
import { Route as AdminCategoriesCategoryIdRouteImport } from './routes/admin/categories/category.$id'

const NotAuthorizedRoute = NotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/admin-logout',
  path: '/admin-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuppliersIndexRoute = AdminSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockBatchesIndexRoute = AdminStockBatchesIndexRouteImport.update({
  id: '/stock-batches/',
  path: '/stock-batches/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductVariantsIndexRoute =
  AdminProductVariantsIndexRouteImport.update({
    id: '/product-variants/',
    path: '/product-variants/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminManufacturersIndexRoute = AdminManufacturersIndexRouteImport.update({
  id: '/manufacturers/',
  path: '/manufacturers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuppliersNewRoute = AdminSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuppliersSupplierIdRoute =
  AdminSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStockBatchesNewRoute = AdminStockBatchesNewRouteImport.update({
  id: '/stock-batches/new',
  path: '/stock-batches/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockBatchesStockBatchIdRoute =
  AdminStockBatchesStockBatchIdRouteImport.update({
    id: '/stock-batches/$stockBatchId',
    path: '/stock-batches/$stockBatchId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductVariantsNewRoute = AdminProductVariantsNewRouteImport.update({
  id: '/product-variants/new',
  path: '/product-variants/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductVariantsProductVariantIdRoute =
  AdminProductVariantsProductVariantIdRouteImport.update({
    id: '/product-variants/$productVariantId',
    path: '/product-variants/$productVariantId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminManufacturersNewRoute = AdminManufacturersNewRouteImport.update({
  id: '/manufacturers/new',
  path: '/manufacturers/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManufacturersManufacturerIdRoute =
  AdminManufacturersManufacturerIdRouteImport.update({
    id: '/manufacturers/$manufacturerId',
    path: '/manufacturers/$manufacturerId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/product/$id',
  path: '/products/product/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesCategoryIdRoute =
  AdminCategoriesCategoryIdRouteImport.update({
    id: '/categories/category/$id',
    path: '/categories/category/$id',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-logout': typeof AdminLogoutRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/manufacturers/$manufacturerId': typeof AdminManufacturersManufacturerIdRoute
  '/admin/manufacturers/new': typeof AdminManufacturersNewRoute
  '/admin/product-variants/$productVariantId': typeof AdminProductVariantsProductVariantIdRoute
  '/admin/product-variants/new': typeof AdminProductVariantsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/stock-batches/$stockBatchId': typeof AdminStockBatchesStockBatchIdRoute
  '/admin/stock-batches/new': typeof AdminStockBatchesNewRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/manufacturers': typeof AdminManufacturersIndexRoute
  '/admin/product-variants': typeof AdminProductVariantsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/stock-batches': typeof AdminStockBatchesIndexRoute
  '/admin/suppliers': typeof AdminSuppliersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/categories/category/$id': typeof AdminCategoriesCategoryIdRoute
  '/admin/products/product/$id': typeof AdminProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-logout': typeof AdminLogoutRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/manufacturers/$manufacturerId': typeof AdminManufacturersManufacturerIdRoute
  '/admin/manufacturers/new': typeof AdminManufacturersNewRoute
  '/admin/product-variants/$productVariantId': typeof AdminProductVariantsProductVariantIdRoute
  '/admin/product-variants/new': typeof AdminProductVariantsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/stock-batches/$stockBatchId': typeof AdminStockBatchesStockBatchIdRoute
  '/admin/stock-batches/new': typeof AdminStockBatchesNewRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/manufacturers': typeof AdminManufacturersIndexRoute
  '/admin/product-variants': typeof AdminProductVariantsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/stock-batches': typeof AdminStockBatchesIndexRoute
  '/admin/suppliers': typeof AdminSuppliersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/categories/category/$id': typeof AdminCategoriesCategoryIdRoute
  '/admin/products/product/$id': typeof AdminProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/admin-logout': typeof AdminLogoutRoute
  '/not-authorized': typeof NotAuthorizedRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/manufacturers/$manufacturerId': typeof AdminManufacturersManufacturerIdRoute
  '/admin/manufacturers/new': typeof AdminManufacturersNewRoute
  '/admin/product-variants/$productVariantId': typeof AdminProductVariantsProductVariantIdRoute
  '/admin/product-variants/new': typeof AdminProductVariantsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/stock-batches/$stockBatchId': typeof AdminStockBatchesStockBatchIdRoute
  '/admin/stock-batches/new': typeof AdminStockBatchesNewRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/suppliers/new': typeof AdminSuppliersNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/manufacturers/': typeof AdminManufacturersIndexRoute
  '/admin/product-variants/': typeof AdminProductVariantsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/stock-batches/': typeof AdminStockBatchesIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/categories/category/$id': typeof AdminCategoriesCategoryIdRoute
  '/admin/products/product/$id': typeof AdminProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-logout'
    | '/not-authorized'
    | '/admin/profile'
    | '/admin/'
    | '/admin/categories/new'
    | '/admin/manufacturers/$manufacturerId'
    | '/admin/manufacturers/new'
    | '/admin/product-variants/$productVariantId'
    | '/admin/product-variants/new'
    | '/admin/products/new'
    | '/admin/stock-batches/$stockBatchId'
    | '/admin/stock-batches/new'
    | '/admin/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/categories'
    | '/admin/manufacturers'
    | '/admin/product-variants'
    | '/admin/products'
    | '/admin/stock-batches'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/categories/category/$id'
    | '/admin/products/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/admin-logout'
    | '/not-authorized'
    | '/admin/profile'
    | '/admin'
    | '/admin/categories/new'
    | '/admin/manufacturers/$manufacturerId'
    | '/admin/manufacturers/new'
    | '/admin/product-variants/$productVariantId'
    | '/admin/product-variants/new'
    | '/admin/products/new'
    | '/admin/stock-batches/$stockBatchId'
    | '/admin/stock-batches/new'
    | '/admin/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/categories'
    | '/admin/manufacturers'
    | '/admin/product-variants'
    | '/admin/products'
    | '/admin/stock-batches'
    | '/admin/suppliers'
    | '/admin/users'
    | '/admin/categories/category/$id'
    | '/admin/products/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/admin-logout'
    | '/not-authorized'
    | '/admin/profile'
    | '/admin/'
    | '/admin/categories/new'
    | '/admin/manufacturers/$manufacturerId'
    | '/admin/manufacturers/new'
    | '/admin/product-variants/$productVariantId'
    | '/admin/product-variants/new'
    | '/admin/products/new'
    | '/admin/stock-batches/$stockBatchId'
    | '/admin/stock-batches/new'
    | '/admin/suppliers/$supplierId'
    | '/admin/suppliers/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/categories/'
    | '/admin/manufacturers/'
    | '/admin/product-variants/'
    | '/admin/products/'
    | '/admin/stock-batches/'
    | '/admin/suppliers/'
    | '/admin/users/'
    | '/admin/categories/category/$id'
    | '/admin/products/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  NotAuthorizedRoute: typeof NotAuthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-authorized': {
      id: '/not-authorized'
      path: '/not-authorized'
      fullPath: '/not-authorized'
      preLoaderRoute: typeof NotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-logout': {
      id: '/admin-logout'
      path: '/admin-logout'
      fullPath: '/admin-logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suppliers/': {
      id: '/admin/suppliers/'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-batches/': {
      id: '/admin/stock-batches/'
      path: '/stock-batches'
      fullPath: '/admin/stock-batches'
      preLoaderRoute: typeof AdminStockBatchesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-variants/': {
      id: '/admin/product-variants/'
      path: '/product-variants'
      fullPath: '/admin/product-variants'
      preLoaderRoute: typeof AdminProductVariantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manufacturers/': {
      id: '/admin/manufacturers/'
      path: '/manufacturers'
      fullPath: '/admin/manufacturers'
      preLoaderRoute: typeof AdminManufacturersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suppliers/new': {
      id: '/admin/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/admin/suppliers/new'
      preLoaderRoute: typeof AdminSuppliersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suppliers/$supplierId': {
      id: '/admin/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/admin/suppliers/$supplierId'
      preLoaderRoute: typeof AdminSuppliersSupplierIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-batches/new': {
      id: '/admin/stock-batches/new'
      path: '/stock-batches/new'
      fullPath: '/admin/stock-batches/new'
      preLoaderRoute: typeof AdminStockBatchesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock-batches/$stockBatchId': {
      id: '/admin/stock-batches/$stockBatchId'
      path: '/stock-batches/$stockBatchId'
      fullPath: '/admin/stock-batches/$stockBatchId'
      preLoaderRoute: typeof AdminStockBatchesStockBatchIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-variants/new': {
      id: '/admin/product-variants/new'
      path: '/product-variants/new'
      fullPath: '/admin/product-variants/new'
      preLoaderRoute: typeof AdminProductVariantsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-variants/$productVariantId': {
      id: '/admin/product-variants/$productVariantId'
      path: '/product-variants/$productVariantId'
      fullPath: '/admin/product-variants/$productVariantId'
      preLoaderRoute: typeof AdminProductVariantsProductVariantIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manufacturers/new': {
      id: '/admin/manufacturers/new'
      path: '/manufacturers/new'
      fullPath: '/admin/manufacturers/new'
      preLoaderRoute: typeof AdminManufacturersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manufacturers/$manufacturerId': {
      id: '/admin/manufacturers/$manufacturerId'
      path: '/manufacturers/$manufacturerId'
      fullPath: '/admin/manufacturers/$manufacturerId'
      preLoaderRoute: typeof AdminManufacturersManufacturerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/categories/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/product/$id': {
      id: '/admin/products/product/$id'
      path: '/products/product/$id'
      fullPath: '/admin/products/product/$id'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/category/$id': {
      id: '/admin/categories/category/$id'
      path: '/categories/category/$id'
      fullPath: '/admin/categories/category/$id'
      preLoaderRoute: typeof AdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminManufacturersManufacturerIdRoute: typeof AdminManufacturersManufacturerIdRoute
  AdminManufacturersNewRoute: typeof AdminManufacturersNewRoute
  AdminProductVariantsProductVariantIdRoute: typeof AdminProductVariantsProductVariantIdRoute
  AdminProductVariantsNewRoute: typeof AdminProductVariantsNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminStockBatchesStockBatchIdRoute: typeof AdminStockBatchesStockBatchIdRoute
  AdminStockBatchesNewRoute: typeof AdminStockBatchesNewRoute
  AdminSuppliersSupplierIdRoute: typeof AdminSuppliersSupplierIdRoute
  AdminSuppliersNewRoute: typeof AdminSuppliersNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminManufacturersIndexRoute: typeof AdminManufacturersIndexRoute
  AdminProductVariantsIndexRoute: typeof AdminProductVariantsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminStockBatchesIndexRoute: typeof AdminStockBatchesIndexRoute
  AdminSuppliersIndexRoute: typeof AdminSuppliersIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCategoriesCategoryIdRoute: typeof AdminCategoriesCategoryIdRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminManufacturersManufacturerIdRoute: AdminManufacturersManufacturerIdRoute,
  AdminManufacturersNewRoute: AdminManufacturersNewRoute,
  AdminProductVariantsProductVariantIdRoute:
    AdminProductVariantsProductVariantIdRoute,
  AdminProductVariantsNewRoute: AdminProductVariantsNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminStockBatchesStockBatchIdRoute: AdminStockBatchesStockBatchIdRoute,
  AdminStockBatchesNewRoute: AdminStockBatchesNewRoute,
  AdminSuppliersSupplierIdRoute: AdminSuppliersSupplierIdRoute,
  AdminSuppliersNewRoute: AdminSuppliersNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminManufacturersIndexRoute: AdminManufacturersIndexRoute,
  AdminProductVariantsIndexRoute: AdminProductVariantsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminStockBatchesIndexRoute: AdminStockBatchesIndexRoute,
  AdminSuppliersIndexRoute: AdminSuppliersIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCategoriesCategoryIdRoute: AdminCategoriesCategoryIdRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  NotAuthorizedRoute: NotAuthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
