/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedAdminProductsRouteImport } from './routes/_authed.admin.products'
import { Route as AuthedAdminCreateUserRouteImport } from './routes/_authed.admin.create-user'
import { Route as AuthedAdminCategoriesRouteImport } from './routes/_authed.admin.categories'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminProductsRoute = AuthedAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminCreateUserRoute = AuthedAdminCreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminCategoriesRoute = AuthedAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/categories': typeof AuthedAdminCategoriesRoute
  '/admin/create-user': typeof AuthedAdminCreateUserRoute
  '/admin/products': typeof AuthedAdminProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/categories': typeof AuthedAdminCategoriesRoute
  '/admin/create-user': typeof AuthedAdminCreateUserRoute
  '/admin/products': typeof AuthedAdminProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_authed/admin/categories': typeof AuthedAdminCategoriesRoute
  '/_authed/admin/create-user': typeof AuthedAdminCreateUserRoute
  '/_authed/admin/products': typeof AuthedAdminProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/categories'
    | '/admin/create-user'
    | '/admin/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/categories'
    | '/admin/create-user'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/admin'
    | '/admin/login'
    | '/_authed/admin/categories'
    | '/_authed/admin/create-user'
    | '/_authed/admin/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/products': {
      id: '/_authed/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthedAdminProductsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/create-user': {
      id: '/_authed/admin/create-user'
      path: '/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AuthedAdminCreateUserRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/categories': {
      id: '/_authed/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthedAdminCategoriesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminCategoriesRoute: typeof AuthedAdminCategoriesRoute
  AuthedAdminCreateUserRoute: typeof AuthedAdminCreateUserRoute
  AuthedAdminProductsRoute: typeof AuthedAdminProductsRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminCategoriesRoute: AuthedAdminCategoriesRoute,
  AuthedAdminCreateUserRoute: AuthedAdminCreateUserRoute,
  AuthedAdminProductsRoute: AuthedAdminProductsRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
